import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Header from './components/header/Header';

const inter = Inter({ subsets: ["latin"] });
// const  KufiArabic = Noto_Kufi_Arabic ({subsets:['arabic'],weight:['300','500']});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}:{children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header/> */}
      <main>
      {children}
      </main>
        </body>
    </html>
  );
}
